### ISSUE TITLE
Update Vamp Elastic Docker Image to ES 5.6

### ISSUE THREAD

**Issue by jason-magnetic-io** [magneticio/elastic#3]
The version of Kibana should also be updated.
The Logstash package can be removed: magneticio/elastic#2

**Comment by jason-magnetic-io** [comment]
I cannot get this to start on DC/OS 1.9 or 1.10. However, I also had trouble getting the official docker image for ES 5.5.2 to start on DC/OS when I tried that.

I wasn't able to start the ES 5 universe package as my cluster doesn't have the required number of private nodes.

The version of ES 5 included in quickstart seems to work.

**Comment by mihaiSimu** [comment]
To deploy on DCOS, make sure you give it enough resources. It worked with 4G and 1 CPU allocated. Closing this.
